//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
using System;
using System.Web.Services;
using System.Diagnostics;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.ComponentModel;
//namespace SATRpaToJson.Model.SATDownloadWS
//{
//    class CFeConsultaLotes
//    {
//    }
//}


//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace SATRpaToJson.Model.SATDownloadWS
{
   


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CfeConsultaLotesSoap", Namespace = "http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultaLotes")]
    public partial class CfeConsultaLotes : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private CfeCabecMsgSoapEntity cfeCabecMsgField;

        private System.Threading.SendOrPostCallback ConsultarLotesEnviadosOperationCompleted;

        /// <remarks/>
        public CfeConsultaLotes()
        {
            this.Url = "https://wssatsp.fazenda.sp.gov.br/CfeConsultarLotes/CfeConsultarLotes.asmx";
        }

        public CfeCabecMsgSoapEntity cfeCabecMsg
        {
            get
            {
                return this.cfeCabecMsgField;
            }
            set
            {
                this.cfeCabecMsgField = value;
            }
        }

        /// <remarks/>
        public event ConsultarLotesEnviadosCompletedEventHandler ConsultarLotesEnviadosCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("cfeCabecMsg", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultar", RequestElementName = "CfeConsultarLotes", RequestNamespace = "http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultaLotes", ResponseElementName = "CfeConsultarLotesResponse", ResponseNamespace = "http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultaLotes", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CfeConsultarLotesResult")]
        public string ConsultarLotesEnviados(string cfeDadosMsg)
        {
            object[] results = this.Invoke("ConsultarLotesEnviados", new object[] {
                        cfeDadosMsg});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginConsultarLotesEnviados(string cfeDadosMsg, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ConsultarLotesEnviados", new object[] {
                        cfeDadosMsg}, callback, asyncState);
        }

        /// <remarks/>
        public string EndConsultarLotesEnviados(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ConsultarLotesEnviadosAsync(string cfeDadosMsg)
        {
            this.ConsultarLotesEnviadosAsync(cfeDadosMsg, null);
        }

        /// <remarks/>
        public void ConsultarLotesEnviadosAsync(string cfeDadosMsg, object userState)
        {
            if ((this.ConsultarLotesEnviadosOperationCompleted == null))
            {
                this.ConsultarLotesEnviadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarLotesEnviadosOperationCompleted);
            }
            this.InvokeAsync("ConsultarLotesEnviados", new object[] {
                        cfeDadosMsg}, this.ConsultarLotesEnviadosOperationCompleted, userState);
        }

        private void OnConsultarLotesEnviadosOperationCompleted(object arg)
        {
            if ((this.ConsultarLotesEnviadosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarLotesEnviadosCompleted(this, new ConsultarLotesEnviadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultaLotes")]
    [System.Xml.Serialization.XmlRootAttribute("cfeCabecMsg", Namespace = "http://www.fazenda.sp.gov.br/sat/wsdl/CfeConsultaLotes", IsNullable = false)]
    public partial class CfeCabecMsgSoapEntity : System.Web.Services.Protocols.SoapHeader
    {

        private string cUFField;

        private string versaoDadosField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string cUF
        {
            get
            {
                return this.cUFField;
            }
            set
            {
                this.cUFField = value;
            }
        }

        /// <remarks/>
        public string versaoDados
        {
            get
            {
                return this.versaoDadosField;
            }
            set
            {
                this.versaoDadosField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ConsultarLotesEnviadosCompletedEventHandler(object sender, ConsultarLotesEnviadosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarLotesEnviadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ConsultarLotesEnviadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
